-- ────────────────────────────────────────────────────────────────────
-- Parent invite codes — the family claims their own child
--
-- THE GAP: list_caregiver_profiles only returns accounts that ALREADY
-- exist, and nothing links a guardian before that. So onboarding a
-- family was: "go sign up → tell me you did → now I'll link you." For
-- every family, at relaunch. There was no way to invite anyone.
--
-- THE SHAPE (deliberate): the tutor issues a code; the PARENT redeems it
-- and links themselves. Nobody grants access on someone else's behalf —
-- the tutor authorizes by issuing, the parent claims by redeeming. Same
-- mental model as the student starter codes Alexus already uses, and
-- the safer design: a mis-click can't hand one family another child's
-- record, because redemption is scoped to whoever holds the code.
--
-- SECURITY:
--  * Codes are HASHED at rest (mirrors student_access_codes.code_hash) —
--    a database leak doesn't hand out portal access.
--  * Issuing is tutor/admin only (checked inside the definer fn, like
--    link_guardian_profile).
--  * Redeeming requires a signed-in caregiver; it links THEIR OWN
--    auth.uid() and nothing else — the caller can't name another profile.
--  * Single use + expiry (14 days) + revocable. Redeeming a code that is
--    used/expired/revoked is refused, and the refusal is deliberately
--    indistinguishable from "wrong code" so codes can't be probed.
--  * The table itself is staff-read-only; redemption goes through the
--    definer fn, so a parent never gets table access.
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.guardian_invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  guardian_row_id uuid NOT NULL REFERENCES public.student_guardians(id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  code_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  used_by_profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  revoked_at timestamptz,
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS guardian_invites_student_idx
  ON public.guardian_invites (student_id, created_at DESC);
CREATE INDEX IF NOT EXISTS guardian_invites_hash_idx
  ON public.guardian_invites (code_hash);
ALTER TABLE public.guardian_invites ENABLE ROW LEVEL SECURITY;
-- Staff can see the invites they've issued (to show status / revoke).
-- Parents never touch this table — redemption is the definer fn below.
DROP POLICY IF EXISTS "guardian invites staff read" ON public.guardian_invites;
CREATE POLICY "guardian invites staff read" ON public.guardian_invites
  FOR SELECT TO authenticated
  USING (public.is_staff());
DROP POLICY IF EXISTS "guardian invites staff write" ON public.guardian_invites;
CREATE POLICY "guardian invites staff write" ON public.guardian_invites
  FOR ALL TO authenticated
  USING (public.is_staff())
  WITH CHECK (public.is_staff());
/** Tutor issues an invite for one guardian row. Returns the invite id;
 *  the CODE itself is generated by the caller and only its hash is
 *  stored, so the plaintext exists exactly once — in the tutor's hands. */
CREATE OR REPLACE FUNCTION public.issue_guardian_invite(
  p_guardian_row_id uuid,
  p_code_hash text
) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_student uuid;
  v_id uuid;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role IN ('admin', 'tutor')
  ) THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;

  SELECT student_id INTO v_student
  FROM public.student_guardians WHERE id = p_guardian_row_id;
  IF v_student IS NULL THEN
    RAISE EXCEPTION 'guardian_not_found';
  END IF;

  -- One live invite per guardian: supersede any outstanding ones so an
  -- old code can't be redeemed after a new one is issued.
  UPDATE public.guardian_invites
  SET revoked_at = now()
  WHERE guardian_row_id = p_guardian_row_id
    AND used_at IS NULL AND revoked_at IS NULL;

  INSERT INTO public.guardian_invites (guardian_row_id, student_id, code_hash, expires_at)
  VALUES (p_guardian_row_id, v_student, p_code_hash, now() + interval '14 days')
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.issue_guardian_invite(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.issue_guardian_invite(uuid, text) TO authenticated;
/** The parent redeems: links their OWN account to the guardian row.
 *  Returns the student's display name on success, NULL on any refusal
 *  (wrong / used / expired / revoked all look identical — no probing). */
CREATE OR REPLACE FUNCTION public.redeem_guardian_invite(p_code_hash text)
RETURNS text
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_invite public.guardian_invites%ROWTYPE;
  v_name text;
BEGIN
  -- NULL uid = not signed in. Guard explicitly: comparisons against NULL
  -- are NULL, not false — the trap this repo has hit before.
  IF v_uid IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT * INTO v_invite
  FROM public.guardian_invites
  WHERE code_hash = p_code_hash
    AND used_at IS NULL
    AND revoked_at IS NULL
    AND expires_at > now()
  LIMIT 1;

  IF v_invite.id IS NULL THEN
    RETURN NULL;
  END IF;

  -- Link the redeemer's own account. p_profile_id can't be supplied by
  -- the caller anywhere in this path.
  UPDATE public.student_guardians
  SET guardian_profile_id = v_uid
  WHERE id = v_invite.guardian_row_id;

  UPDATE public.guardian_invites
  SET used_at = now(), used_by_profile_id = v_uid
  WHERE id = v_invite.id;

  SELECT COALESCE(display_name, first_name, 'your child') INTO v_name
  FROM public.students WHERE id = v_invite.student_id;

  RETURN COALESCE(v_name, 'your child');
END;
$$;
REVOKE EXECUTE ON FUNCTION public.redeem_guardian_invite(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.redeem_guardian_invite(text) TO authenticated;
